version: '3.9'
services:
 web:
  build: .
  container_name: react_project
  ports:
   - "3000:3000"
  volumes:
   - ./my-react-app:/react-app
  stdin_open: true
  tty: true
 app:
  image: node:latest
  container_name: nodeapp_project
  environment:
   DB_HOST: mysql1
   DB_PORT: 3306
   DB_USER: root
   DB_PASSWORD: admin
  ports:
   - "8080:8080"
  command: ["bin/bash"]
  volumes:
   - ./backend:/code

  # important!!!
  depends_on:
   - mysql1 
  stdin_open: true
  tty: true
 mysql1:
  image: mysql:5.7
  platform: linux/amd64
  restart: always
  container_name: db
  environment:
   - MYSQL_ROOT_PASSWORD=admin
  ports:
   - '3306:3306'
  volumes:
   - ./db:/var/lib/mysql
  stdin_open: true
  tty: true
volumes: 
  db:
     driver: local